backend = "glx"
vsync = true

# Rounded corners
corner-radius = 12
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'matrixlock'"
]

# Blur
blur-method = "dual_kawase"
blur-strength = 5
blur-background = true
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'slop'",
  "class_g = 'matrixlock'"
]

# Shadows (optional but looks good with blur)
shadow = true
shadow-radius = 12
shadow-opacity = 0.5
shadow-offset-x = -12
shadow-offset-y = -12
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'matrixlock'",
  "name = 'i3lock'"
]

# Opacity
opacity-rule = [
  "70:class_g = 'Alacritty'",
  "10:name = 'i3lock'",
  "85:class_g = 'matrixlock'"
]

# Fading
fading = true
fade-in-step = 0.03
fade-out-step = 0.03
fade-exclude = [
  "class_g = 'matrixlock'",
  "name = 'i3lock'"
]
