[module/xworkspaces]
type = internal/xworkspaces
label-active            = %name%
label-active-background = ${colors.color2}
label-active-foreground = ${colors.foreground}
label-active-padding    = 1
label-occupied          = %name%
label-occupied-padding  = 1
label-urgent            = %name%
label-urgent-background = ${colors.color4}
label-urgent-padding    = 1
; hide empty workspaces
label-empty =
label-empty-padding = 0

[module/systray]
type = internal/tray

tray-padding = 6
tray-background = ${colors.color3}
format-background = ${colors.color3}

[module/counter]
type = custom/script
exec = ~/.config/polybar/scripts/codeforces_points.py
label = %{T1} %{T-}%output%/15
; label = %{T1} %{T-}1500-1800: %output%
format-background = ${colors.color3}
format-foreground = ${colors.foreground}
label-margin=1pt
interval = 60

[module/polybar-text-1]
type = custom/script
exec = ~/.config/polybar/scripts/codeforces_rating_api.py 1600 1899
label = %{T1} %{T-}Expert: %output%
; label = %{T1} %{T-}1500-1800: %output%
format-background = ${colors.color3}
format-foreground = ${colors.foreground}
label-margin=1pt
interval = 60


[module/polybar-text-2]
type = custom/script
exec = ~/.config/polybar/scripts/codeforces_rating_api.py 1900 2099
label = %{T1} %{T-}Candidate Master: %output%
; label = %{T1} %{T-}1900-2000: %output%
format-background = ${colors.color2}
format-foreground = ${colors.foreground}
interval = 60

[module/polybar-text-3]
type = custom/script
exec = ~/.config/polybar/scripts/codeforces_rating_api.py 2100 2399
label = %{T1} %{T-}Master: %output%
; label = %{T1} %{T-}2100-2300: %output%
format-background = ${colors.color1}
format-foreground = ${colors.foreground}
interval = 60


[module/time]
type = internal/date
interval = 1

time = "%I:%M %p"

format = <label>
format-background = ${colors.color2}
format-foreground = ${colors.foreground}
format-padding = 1
label = %time%

[module/date]
type = internal/date
interval = 1

time = "%b %d"

; time = "%H:%M"
format = <label>
format-background = ${colors.color2}
format-foreground = ${colors.foreground}
format-padding = 1
label = %time%

[module/day]
type = internal/date
interval = 1

time = "%a"
; time = "%H:%M"

format = <label>
format-background = ${colors.color2}
format-foreground = ${colors.foreground}
format-padding = 1
label = %time%

[module/i3]
type = internal/i3
index-sort = true

format = <label-state> <label-mode>
format-background=${colors.color3}

label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.color2}

; ws-icon-0 = 1;A

label-focused = 
label-focused-foreground = ${colors.foreground}
label-focused-padding = 1

label-unfocused =  
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

label-visible= %icon% 
label-visible-foreground = ${colors.foreground}
label-visible-padding = 1

label-urgent= 󰀨
label-urgent-foreground = ${colors.foreground}
label-urgent-padding = 1

[module/margin]
type = custom/text

content = %{T1} %{T-}
content-foreground = ${colors.foreground}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰋋 "
format-volume-prefix-foreground = ${colors.foreground}
format-volume = <label-volume>
format-volume-suffix= " "
format-volume-background= ${colors.color1}
format-muted-background= ${colors.color1}

label-volume = %percentage%%

label-muted = "  󰟎   "
label-muted-foreground = ${colors.foreground}

[module/triangle-left-right-first]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color3}
content-background= ${colors.color2}

[module/triangle-left-right-second]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color2}
content-background= ${colors.color1}

[module/triangle-left-right-third]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color1}

[module/triangle-mid-left]
type = custom/text

; 
content = %{T6}%{T-}
content-foreground = ${colors.color3}
content-background= ${colors.background}

[module/triangle-mid-right]
type = custom/text

; 
content = %{T6}%{T-}
content-foreground = ${colors.color3}
content-background= ${colors.background}


[module/triangle-right-left-first]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color1}

[module/triangle-right-left-second]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color2}
content-background= ${colors.color1}

[module/triangle-right-left-third]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color3}
content-background= ${colors.color2}

[module/soft-right-left]
type = custom/text

content = %{T6}%{T-}
content-foreground = ${colors.color4}
content-background= ${colors.color2}


;----------------------------------------------------------
; OUR MODULES
;----------------------------------------------------------

[module/datetime]
type = internal/date
interval = 1
date = %S:%M:%H  %d-%m-%y
label = %date%
label-foreground = ${colors.foreground}

[module/net-type]
type = custom/script
exec = ~/.config/polybar/scripts/net_type.sh
interval = 5
label = %output%

[module/ip-addr]
type = custom/script
exec = ~/.config/polybar/scripts/ip_addr.sh
interval = 5
label = %output%

[module/cpu]
type = internal/cpu
interval = 1
label = CPU %percentage%%

[module/cpu-temp]
type = custom/script
exec = ~/.config/polybar/scripts/cpu_temp.sh
interval = 2
label = CPU %output%

[module/gpu-temp]
type = custom/script
exec = ~/.config/polybar/scripts/gpu_temp.sh
interval = 2
label = GPU %output%

[module/gpu-load]
type = custom/script
exec = ~/.config/polybar/scripts/gpu_load.sh
interval = 2
label = GPU %output%

[module/gpu-fan]
type = custom/script
exec = ~/.config/polybar/scripts/gpu_fan.sh
interval = 5
label = GPU FAN %output%

[module/memory]
type = internal/memory
interval = 1
warn-percentage = 95
format = <label>
format-warn = <label-warn>
label = RAM %percentage_used%%
label-warn = RAM %gb_used%/%gb_free%

[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
label-mounted = disk %percentage_used%%
label-unmounted = disk N/A

[module/volume]
type = custom/script
exec = ~/.config/polybar/scripts/volume.sh
interval = 1
click-left = pamixer --toggle-mute
scroll-up = pamixer --increase 5
scroll-down = pamixer --decrease 5
format = <label>
label = VOL %output%
